#!/bin/bash
docker run --rm -ti -v ${PWD}:/app/ -p 8888:8888 --hostname localhost --ipc=host mstefferson/tree_bot:latest jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser
#docker run --rm -ti -v ${PWD}:/app/ -p 8888:8888 --ipc=host --hostname localhost mstefferson/tree_bot:latest jupyter notebook --ip 0.0.0.0 --allow-root --no-browser 

